<?php /** @var Codecia_Dynamicfilter_Block_Form $this */ ?>
<?php
    $listConfig = explode(',', Mage::getStoreConfig('codecia_dynamicfilter/settings/filters'));
    $attributes = Mage::getModel('codecia_dynamicfilter/source_attributes')->attrOptions($listConfig);

    $ordem = array('GRUPO','CATEGORIAS','SUBGRUPO','FABRICANTE','MODELOS','MARCA PRODUTO');
    $result = array();

    foreach ($ordem as $name) {

        foreach ($attributes as $key => $value) {

            if (strtolower($name) == strtolower($value['label'])) {

                $result[] = $attributes[$key];
                unset($attributes[$key]);
                break;
            }
        }
    }

    $attributes = array_merge($result, $attributes);

    if(Mage::getStoreConfigFlag('codecia_dynamicfilter/settings/filters')):
?>
<div id="dynamicFilter" class="center">
    <div class="cc-dynamic-filter-title">
        <span><?php echo Mage::getStoreConfig('codecia_dynamicfilter/frontend/title'); ?></span>
        <img class="img-search" src="../skin/frontend/base/default/codecia_dynamicfilter/images/research.svg" title="<?php echo Mage::getStoreConfig('codecia_dynamicfilter/frontend/title'); ?>" width="25" height="25">
        <img class="ajax-request" src="../skin/frontend/base/default/codecia_dynamicfilter/images/ajax-request.svg" alt="LOADING..." width="45" height="45">
    </div>
    <div class="cc-dynamic-filter">
        <div class="cc-filters-grid">
            <?php $i = 1; ?>
            <?php foreach($attributes as $attr): ?>
                <div class="cc-filter-select <?php if ($i > 6): ?>cc-more<?php endif; ?>">
                    <div class="cc-select-border">
                        <label for="select-filter-<?php echo $attr['code']; ?>"><?php echo $attr['label']; ?></label>
                        <select name="select-filter-<?php echo $attr['code']; ?>-[<?php echo $attr['id']; ?>]" id="select-filter-<?php echo $attr['code']; ?>-[<?php echo $attr['id']; ?>]">
                            <option value="" selected><?php //echo $attr['label']; ?></option>
                            <?php foreach ($attr['options'] as $option): ?>
                                <option value="<?php echo $option['value']; ?>"
                                    <?php if (isset($option['url_path'])): ?>
                                        data-url="<?php echo $option['url_path']; ?>"
                                    <?php endif; ?>
                                    ><?php echo $option['label']; ?>
                                    <?php if (Mage::getStoreConfigFlag('codecia_dynamicfilter/frontend/addQty')): ?>
                                        <?php echo ' ('.$option['items_found'].')'; ?>
                                    <?php endif; ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <?php $i++; ?>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="cc-actions">
        <div class="showMore">
            <a class="cc-btn-more cc-plus-filter" style="<?php if(!($i <= 6)): ?>display: none;<?php endif; ?>">Filtros</a>
        </div>
        <div class="btn-search">
            <?php if ($_SERVER['REQUEST_URI'] == '/'): ?>
                <button class="cc-btn-clean-filters">Limpar Filtros</button>
                <button class="cc-btn-filter">Buscar</button>
            <?php endif; ?>
        </div>
    </div>
</div>
<?php endif; ?>